fixed search when entering some series it dosen't give a result
chubimauk/MangaxMangaOpenSources pull request #12
Opened 2022-02-26 03:13 UTC by xOnlyFadi

2022-02-28 06:33 UTC, chubimauk requested changes

2022-02-28 06:33 UTC, chubimauk commented on sources for users/sources-dev/readcomiconline/readcomiconline.js
> +        var directManga = $('.barTitle',$('.rightBox')).first().text().trim()
don't think this is safe

2022-02-28 06:33 UTC, chubimauk commented on sources for users/sources-dev/readcomiconline/readcomiconline.js
> +        if (directManga === 'Cover'){
why is this ===?

2022-03-01 06:04 UTC, xOnlyFadi commented on sources for users/sources-dev/readcomiconline/readcomiconline.js
> +        if (directManga === 'Cover'){
when i use == it dosen't get the name and returns it as search result

2022-03-01 06:04 UTC, xOnlyFadi commented on sources for users/sources-dev/readcomiconline/readcomiconline.js
> +        var directManga = $('.barTitle',$('.rightBox')).first().text().trim()
i probably forgot fixing this

2022-03-01 06:07 UTC, xOnlyFadi reviewed
for the pages push i forgot to make it inside the if and for the === when i used == it did not work at all

2022-03-02 20:25 UTC, chubimauk commented on sources for users/sources-dev/readcomiconline/readcomiconline.js
> +        var directManga = $('.barTitle',$('.rightBox')).first().text().trim()
make it safe before I merge it

2022-03-02 20:26 UTC, chubimauk commented on sources for users/sources-dev/readcomiconline/readcomiconline.js
> +        if (directManga === 'Cover'){
no reason to use ===, change it. you can do `${directManga}` == 'Cover' as a last resort

2022-03-02 20:26 UTC, xOnlyFadi commented on sources for users/sources-dev/readcomiconline/readcomiconline.js
> +        var directManga = $('.barTitle',$('.rightBox')).first().text().trim()
When i go back home i will fix it

2022-03-11 05:37 UTC, chubimauk approved these changes

2022-03-11 05:38 UTC, merged