Fixing Sources
chubimauk/MangaxMangaOpenSources pull request #14
Opened 2022-09-12 22:59 UTC by xOnlyFadi

2022-09-13 03:47 UTC, chubimauk requested changes
Please remove the /NepNep/ folder everywhere.

2022-09-13 03:47 UTC, chubimauk commented on sources for users/sources-dev/NepNep/mangasee/mangasee.js
> +                scanlator: ''
please make scanlator null to fix the duplicate chapters issue

2022-09-13 20:31 UTC, xOnlyFadi commented
when removing /NepNep/ folder do i replace the original mangasee with mine?

2022-09-26 01:33 UTC, chubimauk commented
> when removing /NepNep/ folder do i replace the original mangasee with mine?

yeah that's the idea of version control. The older version will always be there in the previous commit if necessary to look at

2022-10-22 19:10 UTC, xOnlyFadi commented
Fixed things can you merge?

2023-08-27 07:21 UTC, closed without merging